### ISSUE TITLE
setConstantSymbol problem + Solution

### ISSUE THREAD

**Issue by AdamFullstripe** [dfridrich/QRPlatba#10]
Ahoj,

vo funkcii setConstantSymbol nastavujes 

184:         $this->keys['X-CS'] = $cs;

avsak pri vytvarani QR kodu pouzivas 

 71:         'X-KS' => null,
 72:         // Max. 10 znaků - Celé číslo - Konstantní symbol

Preto sa Kontantny sybmol neprenasa do QR kodu

**Comment by dfridrich** [comment]
Opraveno. Diky.
