### ISSUE TITLE
Doplnění popisu

### ISSUE THREAD

**Issue by jprkna** [dfridrich/QRPlatba#11]
Zdravím, 
v popisu, lépe řečeno v prvním příkladu je 2x setSpecificSymbol. V příkladu chybí např. setAmount.

Lze vytvořit QR kód i pro platbu slovenského uživatele na český-slovenský eurový účet s IBAN ?
Mohl bych poprosit o příklad ?

**Comment by dfridrich** [comment]
Ahoj, opraveno a pridan priklad pro SK IBAN.
