### ISSUE TITLE
Problem v setAmount s oddelovacem desetinnych míst a tisíců 

### ISSUE THREAD

**Issue by starosta33** [dfridrich/QRPlatba#13]
```
$this->keys['AM'] = sprintf('%.2f', $amount);
```
bohuzel nefunguje vzdy, QR format ocekava desetinnou tecku

**Comment by pionl** [comment]
Pokud je potřeba vždy stejný formát, použil bych `number_format($amount, 2, ',', '')`

**Comment by starosta33** [comment]
ano, viz muj PR - #14 a zrejme mnou prehlednuty duplikatni #12

**Comment by dfridrich** [comment]
Zamergovano, diky hosi.
