### ISSUE TITLE
Rámeček

### ISSUE THREAD

**Issue by jirikmik** [dfridrich/QRPlatba#6]
Ahoj,

šlo by prosím přidat generování QR kódu včetně rámečku podle grafického manuálu na
https://qr-platba.cz/graficky-manual/
?

J.

**Comment by dfridrich** [comment]
Ahoj, urcite jo, pripravil bych pull request? :-)

**Comment by dfridrich** [comment]
Label vyresen, ramecek prozatim ne.
Viz #31
