### ISSUE TITLE
QRPlatba::accountToIban returns wrong value

### ISSUE THREAD

**Issue by jancinert** [dfridrich/QRPlatba#7]
accountToIban('2600118167/2010﻿') -> CZ9820100000002600118167

**Comment by dfridrich** [comment]
IBAN v prikladu je spatny, spravne je ten, viz nize. Pridany testy, zaviram.

![image](https://user-images.githubusercontent.com/3758421/187086312-f66cb7c0-e288-4019-a51b-946db0bfff00.png)
